injectEnvironmentFiles:
  - .env?

nodeLinker: node-modules

npmScopes:
  fortawesome:
    npmAlwaysAuth: true
    npmAuthToken: "${FONTAWESOME_AUTH_TOKEN}"
    npmRegistryServer: "https://npm.fontawesome.com/"

  bryntum:
    npmAlwaysAuth: true
    npmAuthIdent: maarten..bryntum.com
    npmAuthToken: '${BRYNTUM_AUTH_TOKEN}'
    npmRegistryServer: 'https://npm.bryntum.com'

yarnPath: .yarn/releases/yarn-4.9.2.cjs
